seed: 42
train_data: "data/samples:10_000_train_data_totalnodes:10.pt"
validation_split: 0.2
validation_data: "data/samples:10_000_test_data_totalnodes:10.pt"
batch_size: 32

# Game settings
communication_type: "bee"
mode: "gs"
temperature: 1.5
n_epochs: 100

# Model hyperparameters
max_len: 2
vocab_size: 9
sender_hidden: 32
receiver_hidden: 32
sender_embedding: 32
receiver_embedding: 32

# Graph settings
distance_bins: 10

