communication_type: 'bee'
mode: 'gs'
n_epochs: 100
batch_size: 32
train_data: 'data/samples:10_000_train_data_totalnodes:10.pt'
validation_data: 'data/samples:10_000_test_data_totalnodes:10.pt'

sender_hidden: 64
receiver_hidden: 64
sender_embedding: 32
receiver_embedding: 32
vocab_size: 8

optimizer: 'adam'
lr: 0.005
temperature: 2.5
