communication_type: 'bee'
train_data: 'data/samples:10_000_train_data_totalnodes:10.pt'
test_data:

mode: 'gs'
n_epochs: 10
batch_size: 32
validation_split: 0.2 
num_workers: 4

n_trials: 30 
n_warmup_steps: 5 

lr_range: [0.001, 0.005]
temperature_range: [0.5, 3.0]
hidden_choices: [8, 16, 32, 64]